# Classifying Penguins with Keras

In [164]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [165]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (0.1.6)
Requirement already satisfied: pandas in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from palmerpenguins) (2.1.4)
Requirement already satisfied: numpy in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from palmerpenguins) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from pandas->palmerpenguins) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: six>=1.5 in /Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [166]:
#drop Nan rows
penguins = penguins.dropna()
penguins.shape

(333, 8)

In [167]:
#shuffle the data
penguins = penguins.sample(frac=1, random_state=42).reset_index(drop=True)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007
1,Chinstrap,Dream,50.9,17.9,196.0,3675.0,female,2009
2,Adelie,Torgersen,42.1,19.1,195.0,4000.0,male,2008
3,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,female,2008
4,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008

In [168]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3250.0,39.5,16.7,178.0,True,False
1,3675.0,50.9,17.9,196.0,True,False
2,4000.0,42.1,19.1,195.0,False,True
3,4850.0,46.6,14.2,210.0,True,False
4,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
328,4750.0,49.6,15.0,216.0,False,True
329,3900.0,37.2,19.4,184.0,False,True
330,3200.0,39.7,17.7,193.0,True,False
331,3950.0,45.2,17.8,198.0,True,False
332,3175.0,38.1,17.0,181.0,True,False

In [169]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.152778,0.269091,0.428571,0.101695,1.0,0.0
1,0.270833,0.683636,0.571429,0.406780,1.0,0.0
2,0.361111,0.363636,0.714286,0.389831,0.0,1.0
3,0.597222,0.527273,0.130952,0.644068,1.0,0.0
4,0.375000,0.327273,0.607143,0.338983,0.0,1.0
...,...,...,...,...,...,...
328,0.569444,0.636364,0.226190,0.745763,0.0,1.0
329,0.333333,0.185455,0.750000,0.203390,0.0,1.0
330,0.138889,0.276364,0.547619,0.355932,1.0,0.0
331,0.347222,0.476364,0.559524,0.440678,1.0,0.0
332,0.131944,0.218182,0.464286,0.152542,1.0,0.0

In [170]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()
penguins_y

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)

In [171]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [172]:
model.summary()

Model: "penguin_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_11 (InputLayer)     │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 7)              │            49 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 5)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [173]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) for `plot_model` to work.

In [174]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs=100, validation_split=0.1)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

/Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2241 - loss: 1.1119 - val_accuracy: 0.2353 - val_loss: 1.1131
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3010 - loss: 1.1010 - val_accuracy: 0.1765 - val_loss: 1.1071
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3946 - loss: 1.0951 - val_accuracy: 0.4412 - val_loss: 1.1021
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4348 - loss: 1.0912 - val_accuracy: 0.4412 - val_loss: 1.0986
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4849 - loss: 1.0881 - val_accuracy: 0.4118 - val_loss: 1.0954
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4883 - loss: 1.0856 - val_accuracy: 0.4118 - val_loss: 1.0924
Epoch 7/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4688 - loss: 1.0845

/Users/pmazolew/Documents/GitHub/AdvancedMachineLearning/pycaret-env/lib/python3.10/site-packages/keras/src/backend/tensorflow/nn.py:717: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5017 - loss: 1.0830 - val_accuracy: 0.4118 - val_loss: 1.0900
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4983 - loss: 1.0806 - val_accuracy: 0.4118 - val_loss: 1.0874
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4950 - loss: 1.0781 - val_accuracy: 0.4412 - val_loss: 1.0852
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5151 - loss: 1.0755 - val_accuracy: 0.4412 - val_loss: 1.0824
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5084 - loss: 1.0731 - val_accuracy: 0.4412 - val_loss: 1.0800
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5084 - loss: 1.0705 - val_accuracy: 0.4412 - val_loss: 1.0774
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5017 - loss: 1.0681 - val_accuracy: 0.4412 - val_loss: 1.0751
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5251 - loss: 1.0657 - val_accuracy: 0.4706 - val_loss: 1.0733
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5552 - loss: 1.0630 - val_accuracy: 0.5294 - val_loss: 1.0702
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5886 - loss: 1.0604 - val_accuracy: 0.5588 - val_loss: 1.0680
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6388 - loss: 1.0577 - val_accuracy: 0.5882 - val_loss: 1.0652
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6488 - loss: 1.0550 - val_accuracy: 0.6471 - val_loss: 1.0626
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6722 - loss: 1.0523 - val_accuracy: 0.6765 - val_loss: 1.0596
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6923 - loss: 1.0494 - val_accuracy: 0.6765 - val_loss: 1.0570
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6923 - loss: 1.0466 - val_accuracy: 0.7059 - val_loss: 1.0539
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6890 - loss: 1.0435 - val_accuracy: 0.7059 - val_loss: 1.0516
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6957 - loss: 1.0406 - val_accuracy: 0.6765 - val_loss: 1.0485
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6890 - loss: 1.0375 - val_accuracy: 0.6765 - val_loss: 1.0453
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6923 - loss: 1.0344 - val_accuracy: 0.6765 - val_loss: 1.0430
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6957 - loss: 1.0313 - val_accuracy: 0.6765 - val_loss: 1.0403
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7425 - loss: 1.0278 - val_accuracy: 0.7059 - val_loss: 1.0357
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8060 - loss: 1.0246 - val_accuracy: 0.7059 - val_loss: 1.0324
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 1.0210 - val_accuracy: 0.7353 - val_loss: 1.0296
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 1.0177 - val_accuracy: 0.7353 - val_loss: 1.0259
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 1.0140 - val_accuracy: 0.7941 - val_loss: 1.0215
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8194 - loss: 1.0107 - val_accuracy: 0.7941 - val_loss: 1.0184
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 1.0069 - val_accuracy: 0.8235 - val_loss: 1.0146
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8294 - loss: 1.0033 - val_accuracy: 0.7941 - val_loss: 1.0128
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.9995 - val_accuracy: 0.8529 - val_loss: 1.0087
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8361 - loss: 0.9959 - val_accuracy: 0.8529 - val_loss: 1.0053
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.9919 - val_accuracy: 0.8235 - val_loss: 1.0010
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.9876 - val_accuracy: 0.8235 - val_loss: 0.9970
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8328 - loss: 0.9829 - val_accuracy: 0.8529 - val_loss: 0.9926
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8428 - loss: 0.9779 - val_accuracy: 0.7941 - val_loss: 0.9911
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 0.9730 - val_accuracy: 0.7941 - val_loss: 0.9840
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 0.9680 - val_accuracy: 0.8235 - val_loss: 0.9793
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.9635 - val_accuracy: 0.8235 - val_loss: 0.9764
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.9585 - val_accuracy: 0.8235 - val_loss: 0.9706
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8328 - loss: 0.9535 - val_accuracy: 0.8235 - val_loss: 0.9655
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8361 - loss: 0.9484 - val_accuracy: 0.8235 - val_loss: 0.9613
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.9433 - val_accuracy: 0.8235 - val_loss: 0.9546
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.9380 - val_accuracy: 0.8529 - val_loss: 0.9509
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.9326 - val_accuracy: 0.8529 - val_loss: 0.9453
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8395 - loss: 0.9280 - val_accuracy: 0.8235 - val_loss: 0.9392
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8428 - loss: 0.9225 - val_accuracy: 0.8529 - val_loss: 0.9361
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8361 - loss: 0.9174 - val_accuracy: 0.8235 - val_loss: 0.9294
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.9121 - val_accuracy: 0.8529 - val_loss: 0.9248
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8395 - loss: 0.9065 - val_accuracy: 0.8529 - val_loss: 0.9188
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8395 - loss: 0.9008 - val_accuracy: 0.8235 - val_loss: 0.9116
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8462 - loss: 0.8950 - val_accuracy: 0.8529 - val_loss: 0.9091
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8428 - loss: 0.8896 - val_accuracy: 0.8529 - val_loss: 0.9012
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8428 - loss: 0.8837 - val_accuracy: 0.8529 - val_loss: 0.8950
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.8781 - val_accuracy: 0.8529 - val_loss: 0.8894
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8328 - loss: 0.8721 - val_accuracy: 0.8529 - val_loss: 0.8844
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.8663 - val_accuracy: 0.8529 - val_loss: 0.8786
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.8604 - val_accuracy: 0.8529 - val_loss: 0.8720
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8294 - loss: 0.8540 - val_accuracy: 0.8235 - val_loss: 0.8653
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8328 - loss: 0.8479 - val_accuracy: 0.8235 - val_loss: 0.8598
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8462 - loss: 0.8412 - val_accuracy: 0.8235 - val_loss: 0.8531
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.8348 - val_accuracy: 0.8235 - val_loss: 0.8465
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.8280 - val_accuracy: 0.8235 - val_loss: 0.8400
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8462 - loss: 0.8214 - val_accuracy: 0.8529 - val_loss: 0.8325
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.8138 - val_accuracy: 0.8529 - val_loss: 0.8234
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8495 - loss: 0.8056 - val_accuracy: 0.8529 - val_loss: 0.8139
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.7967 - val_accuracy: 0.8529 - val_loss: 0.8067
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.7879 - val_accuracy: 0.8529 - val_loss: 0.7955
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8562 - loss: 0.7790 - val_accuracy: 0.8529 - val_loss: 0.7880
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8595 - loss: 0.7703 - val_accuracy: 0.8529 - val_loss: 0.7786
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8562 - loss: 0.7610 - val_accuracy: 0.8529 - val_loss: 0.7698
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8562 - loss: 0.7521 - val_accuracy: 0.8529 - val_loss: 0.7611
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8562 - loss: 0.7424 - val_accuracy: 0.8529 - val_loss: 0.7492
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8595 - loss: 0.7331 - val_accuracy: 0.8529 - val_loss: 0.7410
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8528 - loss: 0.7233 - val_accuracy: 0.8529 - val_loss: 0.7315
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8562 - loss: 0.7137 - val_accuracy: 0.8529 - val_loss: 0.7204
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8528 - loss: 0.7044 - val_accuracy: 0.8529 - val_loss: 0.7121
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8528 - loss: 0.6948 - val_accuracy: 0.8529 - val_loss: 0.7017
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8528 - loss: 0.6857 - val_accuracy: 0.8529 - val_loss: 0.6931
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8528 - loss: 0.6766 - val_accuracy: 0.8529 - val_loss: 0.6832
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.6673 - val_accuracy: 0.8529 - val_loss: 0.6725
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.6584 - val_accuracy: 0.8529 - val_loss: 0.6637
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.6499 - val_accuracy: 0.8529 - val_loss: 0.6547
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8361 - loss: 0.6419 - val_accuracy: 0.8529 - val_loss: 0.6454
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8361 - loss: 0.6335 - val_accuracy: 0.8529 - val_loss: 0.6372
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8361 - loss: 0.6255 - val_accuracy: 0.8235 - val_loss: 0.6292
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8227 - loss: 0.6176 - val_accuracy: 0.8235 - val_loss: 0.6229
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.6098 - val_accuracy: 0.7941 - val_loss: 0.6124
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.6022 - val_accuracy: 0.7941 - val_loss: 0.6051
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.5946 - val_accuracy: 0.7941 - val_loss: 0.5965
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.5874 - val_accuracy: 0.7941 - val_loss: 0.5888
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.5802 - val_accuracy: 0.7941 - val_loss: 0.5815
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.5732 - val_accuracy: 0.7941 - val_loss: 0.5752
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.5662 - val_accuracy: 0.7941 - val_loss: 0.5680
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.5589 - val_accuracy: 0.7941 - val_loss: 0.5598
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.5520 - val_accuracy: 0.7941 - val_loss: 0.5517
11/11 - 0s - 2ms/step - accuracy: 0.8048 - loss: 0.5477

In [175]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits = False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(scaled_penguins_x, penguins_y, batch_size = 64, epochs = 100, validation_split = 0.1)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose = 2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8060 - loss: 0.5414 - val_accuracy: 0.7941 - val_loss: 0.5380
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8027 - loss: 0.5297 - val_accuracy: 0.7941 - val_loss: 0.5263
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8027 - loss: 0.5218 - val_accuracy: 0.7941 - val_loss: 0.5192
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.5147 - val_accuracy: 0.7941 - val_loss: 0.5142
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8027 - loss: 0.5089 - val_accuracy: 0.7941 - val_loss: 0.5077
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.5034 - val_accuracy: 0.7941 - val_loss: 0.5009
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4975 - val_accuracy: 0.7941 - val_loss: 0.4962
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4925 - val_accuracy: 0.7941 - val_loss: 0.4912
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4878 - val_accuracy: 0.7941 - val_loss: 0.4845
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4829 - val_accuracy: 0.7941 - val_loss: 0.4809
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4782 - val_accuracy: 0.7941 - val_loss: 0.4771
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4741 - val_accuracy: 0.7941 - val_loss: 0.4712
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4697 - val_accuracy: 0.7941 - val_loss: 0.4670
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4653 - val_accuracy: 0.7941 - val_loss: 0.4631
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4617 - val_accuracy: 0.7941 - val_loss: 0.4590
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4577 - val_accuracy: 0.7941 - val_loss: 0.4543
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4538 - val_accuracy: 0.7941 - val_loss: 0.4505
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4507 - val_accuracy: 0.7941 - val_loss: 0.4465
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7993 - loss: 0.4468 - val_accuracy: 0.7941 - val_loss: 0.4435
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7993 - loss: 0.4429 - val_accuracy: 0.7941 - val_loss: 0.4395
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7993 - loss: 0.4397 - val_accuracy: 0.7941 - val_loss: 0.4370
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4368 - val_accuracy: 0.7941 - val_loss: 0.4341
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4334 - val_accuracy: 0.7941 - val_loss: 0.4297
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4299 - val_accuracy: 0.7941 - val_loss: 0.4261
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4270 - val_accuracy: 0.7941 - val_loss: 0.4228
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4243 - val_accuracy: 0.7941 - val_loss: 0.4194
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4214 - val_accuracy: 0.7941 - val_loss: 0.4169
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4181 - val_accuracy: 0.7941 - val_loss: 0.4143
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7993 - loss: 0.4154 - val_accuracy: 0.7941 - val_loss: 0.4106
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4129 - val_accuracy: 0.7941 - val_loss: 0.4086
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4108 - val_accuracy: 0.7941 - val_loss: 0.4058
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4080 - val_accuracy: 0.7941 - val_loss: 0.4046
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4051 - val_accuracy: 0.7941 - val_loss: 0.4010
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7993 - loss: 0.4034 - val_accuracy: 0.7941 - val_loss: 0.3978
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.4009 - val_accuracy: 0.7941 - val_loss: 0.3961
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3987 - val_accuracy: 0.7941 - val_loss: 0.3932
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.3966 - val_accuracy: 0.7941 - val_loss: 0.3929
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3941 - val_accuracy: 0.7941 - val_loss: 0.3891
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.3932 - val_accuracy: 0.7941 - val_loss: 0.3882
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.3903 - val_accuracy: 0.7941 - val_loss: 0.3853
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.3881 - val_accuracy: 0.7941 - val_loss: 0.3829
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3859 - val_accuracy: 0.7941 - val_loss: 0.3806
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7993 - loss: 0.3846 - val_accuracy: 0.7941 - val_loss: 0.3773
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3824 - val_accuracy: 0.7941 - val_loss: 0.3761
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7993 - loss: 0.3804 - val_accuracy: 0.7941 - val_loss: 0.3730
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3781 - val_accuracy: 0.7941 - val_loss: 0.3721
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7993 - loss: 0.3766 - val_accuracy: 0.7941 - val_loss: 0.3696
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3751 - val_accuracy: 0.7941 - val_loss: 0.3670
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3738 - val_accuracy: 0.7941 - val_loss: 0.3670
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3719 - val_accuracy: 0.7941 - val_loss: 0.3646
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3697 - val_accuracy: 0.7941 - val_loss: 0.3616
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7993 - loss: 0.3680 - val_accuracy: 0.7941 - val_loss: 0.3608
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8027 - loss: 0.3660 - val_accuracy: 0.7941 - val_loss: 0.3585
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8060 - loss: 0.3646 - val_accuracy: 0.7941 - val_loss: 0.3572
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8060 - loss: 0.3624 - val_accuracy: 0.8235 - val_loss: 0.3547
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8060 - loss: 0.3604 - val_accuracy: 0.8235 - val_loss: 0.3528
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.3589 - val_accuracy: 0.8235 - val_loss: 0.3521
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3578 - val_accuracy: 0.8235 - val_loss: 0.3516
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3555 - val_accuracy: 0.8235 - val_loss: 0.3486
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.3538 - val_accuracy: 0.8235 - val_loss: 0.3472
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8194 - loss: 0.3519 - val_accuracy: 0.8235 - val_loss: 0.3445
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8227 - loss: 0.3511 - val_accuracy: 0.8235 - val_loss: 0.3417
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8161 - loss: 0.3491 - val_accuracy: 0.8235 - val_loss: 0.3402
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8127 - loss: 0.3483 - val_accuracy: 0.8235 - val_loss: 0.3387
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8161 - loss: 0.3456 - val_accuracy: 0.8235 - val_loss: 0.3364
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8194 - loss: 0.3449 - val_accuracy: 0.8235 - val_loss: 0.3348
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8261 - loss: 0.3420 - val_accuracy: 0.8235 - val_loss: 0.3349
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8227 - loss: 0.3406 - val_accuracy: 0.8235 - val_loss: 0.3325
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 0.3391 - val_accuracy: 0.8235 - val_loss: 0.3298
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8261 - loss: 0.3374 - val_accuracy: 0.8235 - val_loss: 0.3271
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8261 - loss: 0.3351 - val_accuracy: 0.8235 - val_loss: 0.3246
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8294 - loss: 0.3345 - val_accuracy: 0.8235 - val_loss: 0.3212
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8328 - loss: 0.3322 - val_accuracy: 0.8235 - val_loss: 0.3197
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8294 - loss: 0.3305 - val_accuracy: 0.8235 - val_loss: 0.3171
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8294 - loss: 0.3291 - val_accuracy: 0.8235 - val_loss: 0.3147
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8294 - loss: 0.3263 - val_accuracy: 0.8235 - val_loss: 0.3119
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8395 - loss: 0.3248 - val_accuracy: 0.8235 - val_loss: 0.3088
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8395 - loss: 0.3230 - val_accuracy: 0.8235 - val_loss: 0.3077
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.3204 - val_accuracy: 0.8235 - val_loss: 0.3085
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8395 - loss: 0.3194 - val_accuracy: 0.8235 - val_loss: 0.3058
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8495 - loss: 0.3177 - val_accuracy: 0.8235 - val_loss: 0.3014
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8395 - loss: 0.3154 - val_accuracy: 0.8235 - val_loss: 0.2958
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8462 - loss: 0.3139 - val_accuracy: 0.8235 - val_loss: 0.2942
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8462 - loss: 0.3115 - val_accuracy: 0.8235 - val_loss: 0.2932
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8495 - loss: 0.3097 - val_accuracy: 0.8235 - val_loss: 0.2895
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8495 - loss: 0.3069 - val_accuracy: 0.8529 - val_loss: 0.2819
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8528 - loss: 0.3048 - val_accuracy: 0.8529 - val_loss: 0.2750
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8629 - loss: 0.3007 - val_accuracy: 0.8824 - val_loss: 0.2698
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8595 - loss: 0.2985 - val_accuracy: 0.9118 - val_loss: 0.2650
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8662 - loss: 0.2951 - val_accuracy: 0.9118 - val_loss: 0.2579
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8729 - loss: 0.2926 - val_accuracy: 0.9118 - val_loss: 0.2544
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8662 - loss: 0.2893 - val_accuracy: 0.9118 - val_loss: 0.2443
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8829 - loss: 0.2862 - val_accuracy: 0.9118 - val_loss: 0.2400
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8796 - loss: 0.2845 - val_accuracy: 0.9118 - val_loss: 0.2366
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8763 - loss: 0.2805 - val_accuracy: 0.9412 - val_loss: 0.2273
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8896 - loss: 0.2779 - val_accuracy: 0.9412 - val_loss: 0.2236
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8896 - loss: 0.2742 - val_accuracy: 0.9412 - val_loss: 0.2152
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8997 - loss: 0.2727 - val_accuracy: 0.9412 - val_loss: 0.2150
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8896 - loss: 0.2677 - val_accuracy: 0.9412 - val_loss: 0.2101
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8997 - loss: 0.2663 - val_accuracy: 0.9412 - val_loss: 0.2079
11/11 - 0s - 2ms/step - accuracy: 0.9069 - loss: 0.2573

In [176]:
model_logit_true.predict(scaled_penguins_x)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([[7.33334780e-01, 2.66578019e-01, 8.71651719e-05],
       [2.12871701e-01, 7.86057174e-01, 1.07118790e-03],
       [7.83654273e-01, 2.16071978e-01, 2.73723505e-04],
       [2.84195325e-04, 1.79749858e-02, 9.81740832e-01],
       [7.57729232e-01, 2.41828606e-01, 4.42133605e-04],
       [4.81605202e-01, 5.05342007e-01, 1.30527308e-02],
       [7.67689109e-01, 2.31783330e-01, 5.27624157e-04],
       [2.15230375e-05, 5.33259427e-03, 9.94645953e-01],
       [8.45068280e-06, 3.71860573e-03, 9.96272981e-01],
       [4.98938898e-04, 2.15153154e-02, 9.77985680e-01],
       [4.25985634e-01, 5.52353263e-01, 2.16610264e-02],
       [9.15687919e-01, 8.43078643e-02, 4.11965812e-06],
       [6.98215604e-01, 3.01681906e-01, 1.02440448e-04],
       [8.30705941e-01, 1.69076040e-01, 2.17927081e-04],
       [4.96669412e-01, 5.03113806e-01, 2.16728542e-04],
       [8.16046894e-01, 1.83626786e-01, 3.26309470e-04],
       [8.23945701e-01, 1.75785482e-01, 2.68799282e-04],
       [2.88539479e-04, 1.46008711e-02, 9.85110641e-01],
       [8.27771127e-01, 1.72118470e-01, 1.10354682e-04],
       [3.55445921e-01, 6.43493950e-01, 1.06013450e-03],
       [6.67471230e-01, 3.30874771e-01, 1.65395776e-03],
       [7.41458476e-01, 2.57849604e-01, 6.92019472e-04],
       [1.74117193e-01, 8.12810421e-01, 1.30723482e-02],
       [1.52627079e-04, 1.03804078e-02, 9.89466965e-01],
       [7.66210794e-01, 2.33716428e-01, 7.28420273e-05],
       [7.75414288e-01, 2.24408329e-01, 1.77498820e-04],
       [1.91714658e-04, 1.29004354e-02, 9.86907780e-01],
       [4.53682840e-01, 5.23912132e-01, 2.24050544e-02],
       [6.27645431e-06, 3.30979447e-03, 9.96683955e-01],
       [5.43716609e-01, 4.48855221e-01, 7.42823118e-03],
       [4.55454632e-04, 2.38655377e-02, 9.75678980e-01],
       [3.29968691e-01, 6.69143021e-01, 8.88274633e-04],
       [7.01419055e-01, 2.97752559e-01, 8.28358694e-04],
       [6.63292885e-01, 3.30855608e-01, 5.85158495e-03],
       [2.57120281e-01, 6.07875764e-01, 1.35004014e-01],
       [6.63486540e-01, 3.34293753e-01, 2.21972098e-03],
       [5.74534992e-04, 2.03223806e-02, 9.79103088e-01],
       [2.59274442e-04, 2.70838607e-02, 9.72656786e-01],
       [8.34155679e-01, 1.65545285e-01, 2.98972853e-04],
       [8.23083341e-01, 1.76315337e-01, 6.01228909e-04],
       [7.72865176e-01, 2.27081165e-01, 5.36266234e-05],
       [8.35790813e-01, 1.63964659e-01, 2.44512426e-04],
       [1.64501816e-05, 4.78258543e-03, 9.95201051e-01],
       [2.10350219e-04, 1.19196465e-02, 9.87870038e-01],
       [8.91250670e-01, 1.08720735e-01, 2.85968617e-05],
       [7.44431794e-01, 2.53488243e-01, 2.08000606e-03],
       [6.42390728e-01, 3.54739040e-01, 2.87021697e-03],
       [8.36531878e-01, 1.63382471e-01, 8.56273982e-05],
       [9.04165268e-01, 9.58235711e-02, 1.11288218e-05],
       [2.99107492e-01, 6.25256479e-01, 7.56360888e-02],
       [7.93349028e-01, 2.05953985e-01, 6.96880219e-04],
       [1.28920847e-05, 4.39119386e-03, 9.95595932e-01],
       [4.86797973e-04, 3.05282455e-02, 9.68984902e-01],
       [8.95907462e-01, 1.04070842e-01, 2.16318476e-05],
       [7.81911194e-01, 2.18062103e-01, 2.66393890e-05],
       [4.82599098e-05, 7.40538398e-03, 9.92546439e-01],
       [7.03589618e-01, 2.96362847e-01, 4.74587468e-05],
       [8.77025008e-01, 1.22949921e-01, 2.51011261e-05],
       [9.03885939e-06, 3.81559390e-03, 9.96175289e-01],
       [1.11679336e-04, 1.09461946e-02, 9.88942146e-01],
       [6.59301698e-01, 3.40419143e-01, 2.79205677e-04],
       [4.19646740e-01, 5.49797535e-01, 3.05557344e-02],
       [5.02092957e-01, 4.85625714e-01, 1.22813545e-02],
       [8.31725061e-01, 1.68155253e-01, 1.19785633e-04],
       [9.04820383e-01, 9.51691940e-02, 1.03667398e-05],
       [4.24357086e-01, 5.75574934e-01, 6.79457298e-05],
       [6.50598526e-01, 3.39646727e-01, 9.75473970e-03],
       [4.67759324e-04, 3.70337032e-02, 9.62498546e-01],
       [8.20095122e-01, 1.79674312e-01, 2.30507707e-04],
       [7.34509170e-01, 2.65285134e-01, 2.05679185e-04],
       [8.44054461e-01, 1.55823857e-01, 1.21746838e-04],
       [8.97164941e-01, 1.02814987e-01, 2.00889863e-05],
       [1.68936785e-05, 4.83686896e-03, 9.95146215e-01],
       [3.77218246e-01, 5.78898847e-01, 4.38827462e-02],
       [2.22629678e-04, 1.21138077e-02, 9.87663627e-01],
       [2.65340175e-04, 1.49930222e-02, 9.84741628e-01],
       [8.99563432e-01, 1.00420997e-01, 1.55606722e-05],
       [9.07198846e-01, 9.27922279e-02, 8.91230138e-06],
       [8.47335696e-01, 1.52587488e-01, 7.68200334e-05],
       [9.04621047e-05, 9.42009129e-03, 9.90489483e-01],
       [7.15267837e-01, 2.84676164e-01, 5.59088439e-05],
       [8.20018411e-01, 1.79858834e-01, 1.22807134e-04],
       [3.43225489e-04, 1.43326027e-02, 9.85324264e-01],
       [8.10389042e-01, 1.89491555e-01, 1.19448225e-04],
       [7.58859038e-01, 2.40409091e-01, 7.31875363e-04],
       [6.91557034e-06, 3.43413046e-03, 9.96559024e-01],
       [9.04205084e-01, 9.57837924e-02, 1.10918663e-05],
       [1.13310590e-01, 8.42560351e-01, 4.41291034e-02],
       [7.23249104e-04, 1.88454930e-02, 9.80431259e-01],
       [1.69763371e-04, 1.08983284e-02, 9.88931894e-01],
       [1.69150240e-04, 1.29385693e-02, 9.86892283e-01],
       [5.62050402e-01, 4.30094272e-01, 7.85534643e-03],
       [6.63242638e-01, 3.35093528e-01, 1.66380010e-03],
       [7.45490730e-01, 2.53937602e-01, 5.71601966e-04],
       [7.61605442e-01, 2.38015845e-01, 3.78686644e-04],
       [7.50888944e-01, 2.49062940e-01, 4.81558891e-05],
       [7.80298710e-01, 2.19492987e-01, 2.08270212e-04],
       [1.75361041e-04, 1.09594595e-02, 9.88865256e-01],
       [7.25762725e-01, 2.73493171e-01, 7.44118472e-04],
       [9.09717739e-01, 9.02747512e-02, 7.53129098e-06],
       [7.36943007e-01, 2.62989521e-01, 6.73633913e-05],
       [3.89643162e-01, 5.73498428e-01, 3.68583910e-02],
       [2.85309017e-01, 6.26874030e-01, 8.78168717e-02],
       [8.09179306e-01, 1.90592617e-01, 2.28159741e-04],
       [1.88595550e-05, 5.03852777e-03, 9.94942605e-01],
       [8.25895846e-01, 1.73935249e-01, 1.68963030e-04],
       [1.58140829e-05, 4.71129501e-03, 9.95272875e-01],
       [1.64256871e-05, 4.78789210e-03, 9.95195746e-01],
       [8.21853995e-01, 1.78017318e-01, 1.28594227e-04],
       [2.31707854e-05, 5.45433490e-03, 9.94522452e-01],
       [7.99864650e-01, 1.99913159e-01, 2.22136718e-04],
       [2.56073564e-01, 6.22360766e-01, 1.21565700e-01],
       [3.71050537e-01, 5.39375901e-01, 8.95735025e-02],
       [5.25894902e-05, 7.58598838e-03, 9.92361486e-01],
       [1.43549885e-04, 1.01755820e-02, 9.89680886e-01],
       [2.19893715e-04, 1.19120367e-02, 9.87868011e-01],
       [7.94110656e-01, 2.05741569e-01, 1.47742525e-04],
       [2.30347563e-04, 1.21728014e-02, 9.87596810e-01],
       [5.79279900e-01, 4.16150838e-01, 4.56933677e-03],
       [9.82274105e-06, 3.94861121e-03, 9.96041536e-01],
       [8.77137065e-01, 1.22828037e-01, 3.49179245e-05],
       [1.60127438e-05, 4.70597809e-03, 9.95278001e-01],
       [6.53211355e-01, 3.44046444e-01, 2.74221716e-03],
       [8.96997750e-01, 1.02982424e-01, 1.98703528e-05],
       [8.64979208e-01, 1.34962633e-01, 5.81767126e-05],
       [2.65640438e-01, 6.17835462e-01, 1.16524138e-01],
       [8.20373058e-01, 1.79174706e-01, 4.52244014e-04],
       [8.99905324e-01, 1.00078888e-01, 1.57783143e-05],
       [6.64855003e-01, 3.33536029e-01, 1.60900049e-03],
       [7.82752886e-06, 3.59497638e-03, 9.96397138e-01],
       [7.88647354e-01, 2.11075038e-01, 2.77621439e-04],
       [9.08313870e-01, 9.16766077e-02, 9.50802769e-06],
       [1.95619996e-05, 5.09314192e-03, 9.94887233e-01],
       [7.98671782e-01, 2.00690493e-01, 6.37759047e-04],
       [7.36052513e-01, 2.63890177e-01, 5.72154095e-05],
       [8.14271867e-01, 1.85605288e-01, 1.22807352e-04],
       [2.44365539e-04, 1.77511517e-02, 9.82004464e-01],
       [6.11705184e-01, 3.84943157e-01, 3.35169653e-03],
       [6.24364972e-01, 3.72266769e-01, 3.36823473e-03],
       [8.11700702e-01, 1.87813431e-01, 4.85831173e-04],
       [8.22664559e-01, 1.77183151e-01, 1.52303866e-04],
       [1.05681402e-05, 4.05757967e-03, 9.95931923e-01],
       [8.33266735e-01, 1.66352078e-01, 3.81159974e-04],
       [2.12939382e-01, 7.87044704e-01, 1.59851297e-05],
       [2.83664704e-04, 1.53256981e-02, 9.84390676e-01],
       [6.01584971e-01, 3.98382962e-01, 3.20300169e-05],
       [5.99892111e-04, 4.10106517e-02, 9.58389580e-01],
       [2.90468991e-01, 7.08926857e-01, 6.04196102e-04],
       [1.67482613e-05, 4.81514819e-03, 9.95168030e-01],
       [1.96955516e-04, 1.14599615e-02, 9.88343060e-01],
       [2.05069464e-05, 5.22675784e-03, 9.94752765e-01],
       [7.87718454e-06, 3.61698004e-03, 9.96375203e-01],
       [7.46426582e-01, 2.52982616e-01, 5.90805197e-04],
       [7.08268583e-01, 2.90926039e-01, 8.05378833e-04],
       [1.24282751e-05, 4.31030476e-03, 9.95677352e-01],
       [4.73508262e-04, 1.63175911e-02, 9.83209014e-01],
       [1.61574353e-05, 4.74327430e-03, 9.95240510e-01],
       [8.20017159e-01, 1.79505065e-01, 4.77812981e-04],
       [2.63487291e-05, 5.72037790e-03, 9.94253218e-01],
       [8.80532607e-05, 9.41510033e-03, 9.90496814e-01],
       [6.76718414e-01, 3.21842432e-01, 1.43920840e-03],
       [4.72871959e-01, 5.10741234e-01, 1.63868796e-02],
       [4.77478534e-01, 5.21735430e-01, 7.86022865e-04],
       [2.56591678e-01, 6.42320395e-01, 1.01087838e-01],
       [3.55721044e-04, 2.08728351e-02, 9.78771448e-01],
       [1.04966966e-05, 4.05456917e-03, 9.95935023e-01],
       [3.54341028e-04, 2.38387007e-02, 9.75806832e-01],
       [4.00886114e-04, 1.50619736e-02, 9.84537184e-01],
       [1.73489407e-05, 4.85184835e-03, 9.95130777e-01],
       [7.63153732e-01, 2.36650616e-01, 1.95655957e-04],
       [9.02601182e-01, 9.73859802e-02, 1.28303527e-05],
       [4.94241482e-04, 3.40646133e-02, 9.65441167e-01],
       [4.40738589e-01, 5.31168401e-01, 2.80929636e-02],
       [7.90474176e-01, 2.09327802e-01, 1.97938512e-04],
       [3.89671654e-01, 6.08950496e-01, 1.37786497e-03],
       [4.87826198e-01, 5.11910737e-01, 2.63051450e-04],
       [7.06247628e-01, 2.93030322e-01, 7.22106546e-04],
       [8.31437647e-01, 1.68153435e-01, 4.08951775e-04],
       [7.47075975e-01, 2.51004696e-01, 1.91936432e-03],
       [7.91446924e-01, 2.08471477e-01, 8.14881932e-05],
       [4.83228266e-01, 5.16617477e-01, 1.54361056e-04],
       [7.46226192e-01, 2.53320128e-01, 4.53665853e-04],
       [4.34153364e-04, 1.56097021e-02, 9.83956158e-01],
       [4.29705471e-01, 5.69578528e-01, 7.16078503e-04],
       [7.15736151e-01, 2.83489466e-01, 7.74398388e-04],
       [1.19423690e-04, 1.05925640e-02, 9.89288032e-01],
       [2.34440231e-04, 1.69492532e-02, 9.82816219e-01],
       [7.66404629e-01, 2.33499765e-01, 9.56328804e-05],
       [6.28611028e-01, 3.67628515e-01, 3.76056251e-03],
       [8.42908323e-01, 1.57006368e-01, 8.52594530e-05],
       [5.37390172e-01, 4.53310221e-01, 9.29958560e-03],
       [4.96017069e-01, 4.93688166e-01, 1.02947559e-02],
       [1.10354586e-05, 4.11628094e-03, 9.95872676e-01],
       [5.32487333e-01, 4.64106888e-01, 3.40584572e-03],
       [1.36600866e-05, 4.44786716e-03, 9.95538473e-01],
       [8.02492857e-01, 1.97360471e-01, 1.46689577e-04],
       [7.96736240e-01, 2.03154162e-01, 1.09619265e-04],
       [8.84570420e-01, 1.15399987e-01, 2.95742029e-05],
       [1.64154917e-04, 1.08066266e-02, 9.89029229e-01],
       [7.85450518e-01, 2.13721946e-01, 8.27466836e-04],
       [1.94428401e-04, 1.58471875e-02, 9.83958364e-01],
       [8.43880177e-01, 1.56050369e-01, 6.93808033e-05],
       [6.24710262e-01, 3.75265509e-01, 2.41800026e-05],
       [8.38732421e-01, 1.61172390e-01, 9.51706170e-05],
       [6.57638371e-01, 3.41113657e-01, 1.24801928e-03],
       [6.84541510e-06, 3.42612877e-03, 9.96567011e-01],
       [6.50016955e-06, 3.39103397e-03, 9.96602476e-01],
       [1.20101940e-05, 4.23618732e-03, 9.95751917e-01],
       [3.67386103e-01, 5.89909673e-01, 4.27041613e-02],
       [8.91545177e-01, 1.08426198e-01, 2.87454550e-05],
       [5.51927567e-01, 4.42844987e-01, 5.22747170e-03],
       [1.59117059e-04, 1.14608658e-02, 9.88380015e-01],
       [1.78373120e-05, 4.92585031e-03, 9.95056272e-01],
       [7.84607708e-01, 2.13216960e-01, 2.17534183e-03],
       [8.97771597e-01, 1.02209710e-01, 1.86984198e-05],
       [3.12353998e-01, 6.85670733e-01, 1.97532494e-03],
       [8.11081648e-01, 1.88812226e-01, 1.06071675e-04],
       [1.15594466e-05, 4.19867318e-03, 9.95789826e-01],
       [8.96693170e-01, 1.03286438e-01, 2.03490708e-05],
       [6.12854660e-01, 3.82646263e-01, 4.49915603e-03],
       [6.31620109e-01, 3.64302963e-01, 4.07692790e-03],
       [5.71514308e-01, 4.28358436e-01, 1.27225008e-04],
       [4.74363059e-01, 4.99779880e-01, 2.58570910e-02],
       [1.47524215e-05, 4.59403126e-03, 9.95391250e-01],
       [6.65027916e-01, 3.34875047e-01, 9.70757901e-05],
       [2.66424177e-04, 1.62157919e-02, 9.83517826e-01],
       [1.19696788e-05, 4.22492949e-03, 9.95763063e-01],
       [5.62842488e-01, 4.32683289e-01, 4.47426504e-03],
       [4.61346644e-05, 7.17759412e-03, 9.92776275e-01],
       [7.96866119e-01, 2.03012288e-01, 1.21618963e-04],
       [7.70376682e-01, 2.29261920e-01, 3.61378654e-04],
       [3.30239855e-04, 1.41536808e-02, 9.85516071e-01],
       [8.56336772e-01, 1.43605545e-01, 5.76288512e-05],
       [1.98101225e-05, 5.12098847e-03, 9.94859159e-01],
       [7.52204478e-01, 2.47361675e-01, 4.33893292e-04],
       [1.00843808e-05, 3.95542942e-03, 9.96034443e-01],
       [1.52243108e-01, 8.42140615e-01, 5.61624672e-03],
       [8.03609073e-01, 1.96265295e-01, 1.25583319e-04],
       [4.55409199e-01, 5.41885436e-01, 2.70543923e-03],
       [3.95667812e-05, 6.77021453e-03, 9.93190289e-01],
       [3.34944159e-01, 6.00750506e-01, 6.43053800e-02],
       [7.67476022e-01, 2.32423559e-01, 1.00469195e-04],
       [1.14299746e-05, 4.16721962e-03, 9.95821357e-01],
       [2.50045210e-04, 1.26999673e-02, 9.87049937e-01],
       [1.15680587e-05, 4.20343643e-03, 9.95784998e-01],
       [9.01827574e-01, 9.81589109e-02, 1.35017835e-05],
       [7.81197548e-01, 2.18560770e-01, 2.41665461e-04],
       [6.76367462e-01, 3.23612273e-01, 2.02025476e-05],
       [3.82481900e-04, 1.50625072e-02, 9.84555125e-01],
       [5.52794372e-04, 1.71054471e-02, 9.82341707e-01],
       [1.09699422e-05, 4.10571601e-03, 9.95883346e-01],
       [6.89261019e-01, 3.10685605e-01, 5.33266066e-05],
       [9.25478816e-04, 6.29243329e-02, 9.36150193e-01],
       [8.07958841e-01, 1.91547811e-01, 4.93305968e-04],
       [8.20724607e-01, 1.78726405e-01, 5.49015647e-04],
       [3.67820030e-05, 6.56849891e-03, 9.93394613e-01],
       [8.30545485e-01, 1.69307694e-01, 1.46742866e-04],
       [7.97708035e-01, 2.02144846e-01, 1.47181592e-04],
       [9.05256271e-01, 9.47335735e-02, 1.01539326e-05],
       [8.42287183e-01, 1.57497317e-01, 2.15512831e-04],
       [8.60098302e-01, 1.39854193e-01, 4.74806584e-05],
       [3.10240634e-04, 1.39073888e-02, 9.85782444e-01],
       [7.75634468e-01, 2.24111274e-01, 2.54391081e-04],
       [5.16696393e-01, 4.83134001e-01, 1.69572726e-04],
       [5.59078157e-01, 4.40908581e-01, 1.32536115e-05],
       [2.40927475e-05, 5.53887757e-03, 9.94437039e-01],
       [4.22022343e-01, 5.48782289e-01, 2.91953199e-02],
       [2.71921279e-04, 1.46312881e-02, 9.85096753e-01],
       [3.11698153e-04, 1.48017714e-02, 9.84886587e-01],
       [1.99210190e-04, 1.16466815e-02, 9.88154113e-01],
       [2.61095703e-01, 6.26864612e-01, 1.12039670e-01],
       [3.81767837e-04, 1.48493005e-02, 9.84768867e-01],
       [6.45891488e-01, 3.54076147e-01, 3.24375287e-05],
       [4.04804617e-01, 5.64152420e-01, 3.10428869e-02],
       [5.99413753e-01, 3.95581394e-01, 5.00485115e-03],
       [5.07316377e-04, 1.74685642e-02, 9.82024133e-01],
       [1.32880368e-05, 4.42013843e-03, 9.95566547e-01],
       [9.06242371e-01, 9.37470496e-02, 1.05648314e-05],
       [1.19380435e-04, 9.49933939e-03, 9.90381300e-01],
       [1.76686226e-04, 1.11145442e-02, 9.88708854e-01],
       [9.69612756e-06, 3.92590789e-03, 9.96064425e-01],
       [7.56303012e-01, 2.43324503e-01, 3.72570066e-04],
       [8.95108283e-01, 1.04873300e-01, 1.83772645e-05],
       [7.38716781e-01, 2.60984689e-01, 2.98535160e-04],
       [8.42751861e-01, 1.57154262e-01, 9.38546873e-05],
       [9.03747082e-01, 9.62413400e-02, 1.15239709e-05],
       [6.58738310e-04, 2.60457732e-02, 9.73295450e-01],
       [8.46780360e-01, 1.53159514e-01, 6.01601168e-05],
       [1.63925506e-04, 1.07752550e-02, 9.89060879e-01],
       [6.98615730e-01, 3.00465524e-01, 9.18658974e-04],
       [7.91418254e-01, 2.08369061e-01, 2.12612082e-04],
       [4.84259799e-05, 7.37475557e-03, 9.92576838e-01],
       [1.26143932e-04, 9.65865608e-03, 9.90215182e-01],
       [8.34597647e-01, 1.65238485e-01, 1.63932287e-04],
       [8.28365982e-01, 1.71371967e-01, 2.62069807e-04],
       [3.85765612e-01, 6.13256454e-01, 9.77936783e-04],
       [1.17039481e-05, 4.17981716e-03, 9.95808542e-01],
       [2.93664575e-01, 7.01137841e-01, 5.19759208e-03],
       [6.57681108e-01, 3.41172129e-01, 1.14679360e-03],
       [5.59089601e-01, 4.31880623e-01, 9.02979448e-03],
       [1.89105795e-05, 5.06391795e-03, 9.94917095e-01],
       [8.26412678e-01, 1.73280552e-01, 3.06747184e-04],
       [7.81375349e-01, 2.18494147e-01, 1.30474160e-04],
       [1.46598550e-05, 4.57533682e-03, 9.95410025e-01],
       [1.45674303e-05, 4.57513938e-03, 9.95410264e-01],
       [2.44417071e-01, 6.18885815e-01, 1.36696994e-01],
       [4.61312768e-04, 1.93280261e-02, 9.80210662e-01],
       [1.57100862e-04, 1.18393749e-02, 9.88003492e-01],
       [8.00473750e-01, 1.99322000e-01, 2.04166921e-04],
       [8.28379393e-01, 1.71405077e-01, 2.15600274e-04],
       [1.51663644e-05, 4.66469117e-03, 9.95320201e-01],
       [2.61341393e-05, 5.71470568e-03, 9.94259119e-01],
       [8.93723965e-01, 1.06250428e-01, 2.55819432e-05],
       [7.63023447e-04, 3.28696743e-02, 9.66367304e-01],
       [7.16119111e-01, 2.82831341e-01, 1.04951544e-03],
       [5.82302164e-04, 2.39692125e-02, 9.75448489e-01],
       [4.41034883e-01, 5.58561444e-01, 4.03672602e-04],
       [2.78587453e-04, 1.42508950e-02, 9.85470533e-01],
       [3.25718194e-01, 6.70063555e-01, 4.21829848e-03],
       [1.35676864e-05, 4.44215722e-03, 9.95544255e-01],
       [8.31435740e-01, 1.68231815e-01, 3.32391472e-04],
       [3.39662016e-04, 1.83965825e-02, 9.81263816e-01],
       [8.95386577e-01, 1.04590937e-01, 2.25215117e-05],
       [7.87998497e-01, 2.11771622e-01, 2.29818368e-04],
       [2.81942630e-04, 2.04754993e-02, 9.79242563e-01],
       [6.69854343e-01, 3.28694105e-01, 1.45158789e-03],
       [2.75172591e-01, 7.24079728e-01, 7.47682760e-04],
       [8.43253672e-01, 1.56606808e-01, 1.39500902e-04],
       [4.41743432e-05, 6.98228832e-03, 9.92973566e-01],
       [9.02040839e-01, 9.79459137e-02, 1.32681143e-05],
       [7.75091529e-01, 2.24715769e-01, 1.92784049e-04],
       [2.61924297e-01, 7.29295433e-01, 8.78032297e-03],
       [7.69978583e-01, 2.29895949e-01, 1.25516875e-04]], dtype=float32)

In [177]:
penguins['species']

0         Adelie
1      Chinstrap
2         Adelie
3         Gentoo
4         Adelie
         ...
328       Gentoo
329       Adelie
330       Adelie
331    Chinstrap
332       Adelie
Name: species, Length: 333, dtype: object

In [178]:
penguins_y

array([0, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1,
       0, 2, 0, 1, 0, 0, 2, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 1,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2,
       0, 1, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 0,
       2, 2, 2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 2, 0, 0, 2, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0,
       2, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 0, 2, 0, 1,
       1, 1, 0, 2, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 0, 0,
       2, 0, 2, 0, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 2, 2, 1, 2, 2,
       0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0,
       0, 1, 0], dtype=int8)